  version: '3'
  services:
    jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins
      privileged: true
      ports:
        - "8080:8080"
        - "50000:50000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - jenkins_home:/var/jenkins_home
      environment:
        - JENKINS_OPTS=--prefix=/jenkins
        - JAVA_OPTS= Djenkins.install.runSetupWizard=false
      depends_on:
        - dind


  dind:
    image: docker:20-dind
    container_name: dind
    privileged: true 
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - dind-storage:/var/lib/docker


  volumes:
    jenkins_home:
    dind-storage:
